DROP TABLE IF EXISTS #ec_test;

SELECT *
INTO #ec_test
FROM (
	SELECT *
	FROM @SCHEMA.@CENSUS_LOCATION cl
	INNER JOIN #enc_counts e ON e.patid = cl.PERSON_ID COLLATE SQL_Latin1_General_CP1_CS_AS
	WHERE loc_start <= CONVERT(DATETIME, '12-31-' + CAST(yr AS VARCHAR(4)))
	) a;
