DROP TABLE IF EXISTS #TYPE_ENC_OUT;

SELECT a.linkid
	,e.ADATE AS admit_date
	,e.ENCTYPE AS enc_type
	,e.PROVIDER
	,ps.SPECIALTY
	,ps.SPECIALTY2
	,ps.SPECIALTY3
	,ps.SPECIALTY4
	,PROVIDER_TYPE
INTO #TYPE_ENC_OUT
FROM #anchor_date a
JOIN @SCHEMA.@ENCOUNTERS e ON e.PERSON_ID = a.patid
JOIN @SCHEMA.@PROVIDER_SPECIALTY ps ON e.PROVIDER = ps.PROVIDER
WHERE e.ADATE >= DATEADD(month, -8, a.measure_date)
ORDER BY linkid;

